# Generated by Django 5.1.1 on 2024-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comelive", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(unique=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(unique=True, verbose_name="Start date"),
        ),
    ]
