# Generated by Django 5.1.1 on 2024-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'ad', 'verbose_name_plural': 'ads'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='rooms',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
