# Generated by Django 5.1.1 on 2024-09-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ad_options_alter_ad_price_alter_ad_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-id'], 'verbose_name': 'ad', 'verbose_name_plural': 'ads'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
